version: "2.1"
services:
  common:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RESOLWE_DJANGO_DEBUG=${RESOLWE_DJANGO_DEBUG:-1}
      - RESOLWE_REDIS_HOST=${RESOLWE_REDIS_HOST:-redis}
      - RESOLWE_REDIS_PORT=${RESOLWE_REDIS_PORT:-6379}
      - RESOLWE_REDIS_DB=${RESOLWE_REDIS_DB:-0}
      - RESOLWE_POSTGRESQL_NAME=${RESOLWE_POSTGRESQL_NAME:-resolwe-bio}
      - RESOLWE_POSTGRESQL_USER=${RESOLWE_POSTGRESQL_USER:-resolwe}
      - RESOLWE_POSTGRESQL_HOST=${RESOLWE_POSTGRESQL_HOST:-postgresql}
      - RESOLWE_POSTGRESQL_PORT=${RESOLWE_POSTGRESQL_PORT:-5432}
      - RESOLWE_ES_HOST=${RESOLWE_ES_HOST:-elasticsearch}
      - RESOLWE_ES_PORT=${RESOLWE_ES_PORT:-9200}
      - RESOLWE_SECRET_KEY=${RESOLWE_SECRET_KEY:-1}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME:-admin}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL:-admin@test.com}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD:-admin1test}