#
# Development configuration of dependent services for Docker Compose.
#
postgresql:
    image: postgres:9.4
    environment:
        POSTGRES_USER: resolwe
        POSTGRES_DB: resolwe-genialis
    ports:
        - "5432:5432"
redis:
    image: redis:3.2
    ports:
        - "56381:6379"
elasticsearch:
    image: elasticsearch:2.4
    ports:
        - "9200:9200"