version: "2.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-for-db.sh",
      "${RESOLWE_POSTGRESQL_HOST:-postgresql}",
      "${RESOLWE_POSTGRESQL_PORT:-5432}",
      "${RESOLWE_POSTGRESQL_USER:-resolwe}",
      "${RESOLWE_POSTGRESQL_NAME:-resolwe-bio}",
      "${RESOLWE_ES_HOST:-elasticsearch}",
      "${RESOLWE_ES_PORT:-9200}",
      "./runserver.sh"]
    ports:
      - "${PROCESS_ENGINE_PORT:-7600}:8000"
    links:
      - redis
      - postgresql
      - elasticsearch
    environment:
      - RESOLWE_DJANGO_DEBUG=${RESOLWE_DJANGO_DEBUG:-1}
      - RESOLWE_REDIS_HOST=${RESOLWE_REDIS_HOST:-redis}
      - RESOLWE_REDIS_PORT=${RESOLWE_REDIS_PORT:-6379}
      - RESOLWE_REDIS_DB=${RESOLWE_REDIS_DB:-0}
      - RESOLWE_POSTGRESQL_NAME=${RESOLWE_POSTGRESQL_NAME:-resolwe-bio}
      - RESOLWE_POSTGRESQL_USER=${RESOLWE_POSTGRESQL_USER:-resolwe}
      - RESOLWE_POSTGRESQL_HOST=${RESOLWE_POSTGRESQL_HOST:-postgresql}
      - RESOLWE_POSTGRESQL_PORT=${RESOLWE_POSTGRESQL_PORT:-5432}
      - RESOLWE_ES_HOST=${RESOLWE_ES_HOST:-elasticsearch}
      - RESOLWE_ES_PORT=${RESOLWE_ES_PORT:-9200}
      - RESOLWE_SECRET_KEY=${RESOLWE_SECRET_KEY:-1}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME:-admin}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL:-admin@test.com}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD:-admin1test}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
  postgresql:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=${RESOLWE_POSTGRESQL_USER:-resolwe}
      - POSTGRES_DB=${RESOLWE_POSTGRESQL_NAME:-resolwe-bio}
    ports:
      - "${RESOLWE_POSTGRESQL_PORT:-5432}"
  redis:
    image: redis:3.2
    ports:
      - "${RESOLWE_REDIS_PORT:-6379}"
  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - "${RESOLWE_ES_PORT:-9200}"
